/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as BuyGoalIdRouteImport } from './routes/buy.$goalId'
import { Route as CircleGoalIdRouteImport } from './routes/circle.$goalId'
import { Route as ContributeGoalIdRouteImport } from './routes/contribute.$goalId'
import { Route as GoalGoalIdRouteImport } from './routes/goal.$goalId'
import { Route as ReceiptGoalIdRouteImport } from './routes/receipt.$goalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyGoalIdRoute = BuyGoalIdRouteImport.update({
  id: '/buy/$goalId',
  path: '/buy/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleGoalIdRoute = CircleGoalIdRouteImport.update({
  id: '/circle/$goalId',
  path: '/circle/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeGoalIdRoute = ContributeGoalIdRouteImport.update({
  id: '/contribute/$goalId',
  path: '/contribute/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalGoalIdRoute = GoalGoalIdRouteImport.update({
  id: '/goal/$goalId',
  path: '/goal/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptGoalIdRoute = ReceiptGoalIdRouteImport.update({
  id: '/receipt/$goalId',
  path: '/receipt/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/buy/$goalId': typeof BuyGoalIdRoute
  '/circle/$goalId': typeof CircleGoalIdRoute
  '/contribute/$goalId': typeof ContributeGoalIdRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/receipt/$goalId': typeof ReceiptGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/buy/$goalId': typeof BuyGoalIdRoute
  '/circle/$goalId': typeof CircleGoalIdRoute
  '/contribute/$goalId': typeof ContributeGoalIdRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/receipt/$goalId': typeof ReceiptGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/buy/$goalId': typeof BuyGoalIdRoute
  '/circle/$goalId': typeof CircleGoalIdRoute
  '/contribute/$goalId': typeof ContributeGoalIdRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
  '/receipt/$goalId': typeof ReceiptGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/discover'
    | '/emergency'
    | '/buy/$goalId'
    | '/circle/$goalId'
    | '/contribute/$goalId'
    | '/goal/$goalId'
    | '/receipt/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/discover'
    | '/emergency'
    | '/buy/$goalId'
    | '/circle/$goalId'
    | '/contribute/$goalId'
    | '/goal/$goalId'
    | '/receipt/$goalId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/discover'
    | '/emergency'
    | '/buy/$goalId'
    | '/circle/$goalId'
    | '/contribute/$goalId'
    | '/goal/$goalId'
    | '/receipt/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  EmergencyRoute: typeof EmergencyRoute
  BuyGoalIdRoute: typeof BuyGoalIdRoute
  CircleGoalIdRoute: typeof CircleGoalIdRoute
  ContributeGoalIdRoute: typeof ContributeGoalIdRoute
  GoalGoalIdRoute: typeof GoalGoalIdRoute
  ReceiptGoalIdRoute: typeof ReceiptGoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$goalId': {
      id: '/buy/$goalId'
      path: '/buy/$goalId'
      fullPath: '/buy/$goalId'
      preLoaderRoute: typeof BuyGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/$goalId': {
      id: '/circle/$goalId'
      path: '/circle/$goalId'
      fullPath: '/circle/$goalId'
      preLoaderRoute: typeof CircleGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/$goalId': {
      id: '/contribute/$goalId'
      path: '/contribute/$goalId'
      fullPath: '/contribute/$goalId'
      preLoaderRoute: typeof ContributeGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/$goalId': {
      id: '/goal/$goalId'
      path: '/goal/$goalId'
      fullPath: '/goal/$goalId'
      preLoaderRoute: typeof GoalGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$goalId': {
      id: '/receipt/$goalId'
      path: '/receipt/$goalId'
      fullPath: '/receipt/$goalId'
      preLoaderRoute: typeof ReceiptGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  EmergencyRoute: EmergencyRoute,
  BuyGoalIdRoute: BuyGoalIdRoute,
  CircleGoalIdRoute: CircleGoalIdRoute,
  ContributeGoalIdRoute: ContributeGoalIdRoute,
  GoalGoalIdRoute: GoalGoalIdRoute,
  ReceiptGoalIdRoute: ReceiptGoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
